import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Bem vindo ao bom verde</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao <span className={styles.bomverdeTitle}>Bom Verde</span>
        </h1>

        <p className={styles.description}>
          Comece agora mesmo a usar nosso app e boas compras!
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Produtos &rarr;</h2>
            <p>
              Aprenda a cadastrar produtos dando visibilidade aos clintes e
              administrar seu estoque!
            </p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Pagamentos &rarr;</h2>
            <p>
              Saiba como você pode gerenciar seus clientes e receber pagamentos
              pelo site
            </p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Clientes &rarr;</h2>
            <p>Gerencie produtos e promoções atraindo clientes e compras!</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Relatórios &rarr;</h2>
            <p>Gere relatórios sobre seus produtos e vendas.</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
